[features]
seeds = false
skip-lint = false

[programs.localnet]
access_control = "5X3NaJMZ9py5VmGHvXgFCYb9Cr4hFQthjqveTKCqcTqJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
